# Generated by Django 3.0.8 on 2020-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200925_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сustomer',
            name='avatar',
            field=models.URLField(max_length=380, null=True),
        ),
    ]
