# Generated by Django 3.0.8 on 2020-10-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200925_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
