# Generated by Django 3.0.8 on 2020-10-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='unread_messages',
        ),
        migrations.AlterField(
            model_name='lead',
            name='message_unread',
            field=models.IntegerField(default=0),
        ),
    ]
