# Generated by Django 3.0.8 on 2020-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20201106_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='customers',
            field=models.ManyToManyField(related_name='integrations_customers', to='crm.Сustomer'),
        ),
    ]
