# Generated by Django 3.0.8 on 2020-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
