# Generated by Django 3.0.8 on 2020-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0002_message_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='message',
            name='api_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
