# Generated by Django 3.0.8 on 2020-10-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0004_message_ppt_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ppt_url',
            new_name='ptt_url',
        ),
    ]
