# Generated by Django 3.0.8 on 2020-10-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0005_auto_20201020_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
