# Generated by Django 3.0.8 on 2020-10-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0007_remove_message_unread_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplatedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiId', models.CharField(blank=True, max_length=180, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complated_task_message', to='social_messenger.Message')),
            ],
            options={
                'db_table': 'complated_task',
            },
        ),
    ]
