# Generated by Django 3.0.8 on 2020-10-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0008_complatedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photoBase64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
