# Generated by Django 3.0.8 on 2020-10-31 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0009_message_photobase64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='photo',
        ),
        migrations.AlterField(
            model_name='complatedtask',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complated_task_message', to='social_messenger.Message'),
        ),
    ]
