# Generated by Django 3.0.8 on 2020-10-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_messenger', '0010_auto_20201031_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='photoBase64',
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='complatedtask',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complated_task_message', to='social_messenger.Message'),
        ),
    ]
