# Generated by Django 3.0.8 on 2020-11-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(related_name='rel_materials', through='figma.ProductMaterial', to='figma.Material'),
        ),
    ]
